/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robot.glb --types --output app/components/render/Robot.tsx 
Author: mikeramos (https://sketchfab.com/mikeramos)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/360-sphere-robot-a0bd28b7133648848427a5c27975611b
Title: 360 Sphere Robot
*/

import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
// import { GLTF } from "three-stdlib";
import { JSX, useEffect, useRef } from "react";

// type ActionName = "sphere body|sphere bodyAction";

// interface GLTFAction extends THREE.AnimationClip {
//   name: ActionName;
// }

// type GLTFResult = GLTF & {
//   nodes: {
//     sphere_body_glossy_paint_white_0: THREE.Mesh;
//     sphere_body_black_matte_0: THREE.Mesh;
//     sphere_body_metal_0: THREE.Mesh;
//     sphere_body_eyes_light_0: THREE.Mesh;
//     sphere_body_dark_glass_0: THREE.Mesh;
//     sphere_body_black_matter_blender_0: THREE.Mesh;
//     sphere_body_thruster_light_0: THREE.Mesh;
//     sphere_body_blender_glass_0: THREE.Mesh;
//   };
//   materials: {
//     glossy_paint_white: THREE.MeshStandardMaterial;
//     black_matte: THREE.MeshStandardMaterial;
//     metal: THREE.MeshStandardMaterial;
//     eyes_light: THREE.MeshStandardMaterial;
//     dark_glass: THREE.MeshStandardMaterial;
//     black_matter_blender: THREE.MeshStandardMaterial;
//     thruster_light: THREE.MeshStandardMaterial;
//     blender_glass: THREE.MeshStandardMaterial;
//   };
//   animations: GLTFAction[];
// };

export function Model({ mouse,
  ...props
}: JSX.IntrinsicElements["group"] & { mouse?: React.MutableRefObject<THREE.Vector2> }) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF("/robot.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      const firstAnimation = animations[0].name;
      actions[firstAnimation]?.play();
    }
  }, [actions, animations]);

  useFrame((state, delta) => {
    const currentMouse = mouse ? mouse.current : state.pointer;

    const targetRotY = currentMouse.x * 0.4; // Ajusta el rango horizontal
    const targetRotX = currentMouse.y * -0.3; // Ajusta el rango vertical (negativo invierte el eje)

    // Suavizado Lerp (Linear Interpolation) paso a paso
    if (group.current) {

    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      targetRotY,
      delta * 15,
    );
    group.current.rotation.x = THREE.MathUtils.lerp(
      group.current.rotation.x,
      targetRotX,
      delta * 15,
    );
  }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.017}
        >
          <group
            name="8cfcbf279e5145b29fef01b31cc1d658fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="sphere_body"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="sphere_body_glossy_paint_white_0"
                    geometry={
                      (nodes.sphere_body_glossy_paint_white_0 as THREE.Mesh)
                        .geometry
                    }
                    material={materials.glossy_paint_white}
                  />
                  <mesh
                    name="sphere_body_black_matte_0"
                    geometry={
                      (nodes.sphere_body_black_matte_0 as THREE.Mesh).geometry
                    }
                    material={materials.black_matte}
                  />
                  <mesh
                    name="sphere_body_metal_0"
                    geometry={
                      (nodes.sphere_body_metal_0 as THREE.Mesh).geometry
                    }
                    material={materials.metal}
                  />
                  <mesh
                    name="sphere_body_eyes_light_0"
                    geometry={
                      (nodes.sphere_body_eyes_light_0 as THREE.Mesh).geometry
                    }
                    material={materials.eyes_light}
                  />
                  <mesh
                    name="sphere_body_dark_glass_0"
                    geometry={
                      (nodes.sphere_body_dark_glass_0 as THREE.Mesh).geometry
                    }
                    material={materials.dark_glass}
                  />
                  <mesh
                    name="sphere_body_black_matter_blender_0"
                    geometry={
                      (nodes.sphere_body_black_matter_blender_0 as THREE.Mesh)
                        .geometry
                    }
                    material={materials.black_matter_blender}
                  />
                  <mesh
                    name="sphere_body_thruster_light_0"
                    geometry={
                      (nodes.sphere_body_thruster_light_0 as THREE.Mesh)
                        .geometry
                    }
                    material={materials.thruster_light}
                  />
                  <mesh
                    name="sphere_body_blender_glass_0"
                    geometry={
                      (nodes.sphere_body_blender_glass_0 as THREE.Mesh).geometry
                    }
                    material={materials.blender_glass}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot.glb");
